CREATE TABLE IF NOT EXISTS fruits (
    id int(11) NOT NULL AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    origin varchar(20) NOT NULL,
    stock int(11) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO fruits (name, origin, stock) VALUES
('apple', 'spain', 44),
('apple', 'italy', 5),
('apple', 'britain', 21),
('apple', 'ireland', 29),
('apple', 'portugal', 21),
('orange', 'spain', 95),
('orange', 'italy', 71),
('orange', 'britain', 19),
('orange', 'ireland', 29),
('orange', 'portugal', 64),
('banana', 'spain', 39),
('banana', 'italy', 72),
('banana', 'britain', 56),
('banana', 'ireland', 87),
('banana', 'portugal', 95),
('apricot', 'spain', 15),
('apricot', 'italy', 86),
('apricot', 'britain', 82),
('apricot', 'ireland', 25),
('apricot', 'portugal', 70),
('strawberry', 'spain', 72),
('strawberry', 'italy', 11),
('strawberry', 'britain', 60),
('strawberry', 'ireland', 81),
('strawberry', 'portugal', 39),
('pear', 'spain', 58),
('pear', 'italy', 67),
('pear', 'britain', 85),
('pear', 'ireland', 87),
('pear', 'portugal', 59),
('cherry', 'spain', 53),
('cherry', 'italy', 31),
('cherry', 'britain', 64),
('cherry', 'ireland', 74),
('cherry', 'portugal', 61),
('grape', 'spain', 85),
('grape', 'italy', 69),
('grape', 'britain', 31),
('grape', 'ireland', 4),
('grape', 'portugal', 99),
('kiwifruit', 'spain', 95),
('kiwifruit', 'italy', 43),
('kiwifruit', 'britain', 70),
('kiwifruit', 'ireland', 51),
('kiwifruit', 'portugal', 30),
('pineapple', 'spain', 65),
('pineapple', 'italy', 67),
('pineapple', 'britain', 15),
('pineapple', 'ireland', 46),
('pineapple', 'portugal', 93);